### ISSUE TITLE
Images For Wiki

### ISSUE THREAD

**Issue by rjcrjc** [rjcrjc/rice-eclipse-mk1-1#1]
This is an empty issue that contains images used in the wiki.

**Comment by luke-avionics** [comment]
![ignition](https://user-images.githubusercontent.com/16768961/30515174-a25151c6-9ae8-11e7-92b2-06813214b4ab.PNG)




Ignition system

**Comment by luke-avionics** [comment]
![ignition_modified](https://user-images.githubusercontent.com/16768961/30515213-620911e8-9ae9-11e7-97f8-bdc53269b9d0.PNG)

Ignition system (without alarm battery)
